// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // `prisma dev` no permite crear la shadow DB al vuelo; usamos la que
    // expone en un puerto aparte para que `migrate dev` funcione en local.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
